package com.awscalculator.backend.calculation;

import com.awscalculator.backend.resource.ResourceType;
import java.math.BigDecimal;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class ResourcePricingRuleInitializer implements ApplicationRunner {

    private final ResourcePricingRuleRepository resourcePricingRuleRepository;

    @Override
    public void run(ApplicationArguments args) {
        for (ResourcePricingRule rule : SEED_RULES) {
            resourcePricingRuleRepository.findByResourceTypeAndComponentName(rule.getResourceType(), rule.getComponentName())
                    .ifPresentOrElse(
                            existing -> existing.updateFrom(rule),
                            () -> resourcePricingRuleRepository.save(rule)
                    );
        }
    }

    private static final List<ResourcePricingRule> SEED_RULES = List.of(
            rule(ResourceType.ECS, "vcpu-x86", "fargate_vcpu_hour_x86", null, "cpu", "tasks", null, true,
                    "architecture", "x86_64", null, null, 10),
            rule(ResourceType.ECS, "memory-x86", "fargate_gb_hour_x86", null, "memory", "tasks", null, true,
                    "architecture", "x86_64", null, null, 20),
            rule(ResourceType.ECS, "vcpu-arm", "fargate_vcpu_hour_arm", null, "cpu", "tasks", null, true,
                    "architecture", "arm64", null, null, 30),
            rule(ResourceType.ECS, "memory-arm", "fargate_gb_hour_arm", null, "memory", "tasks", null, true,
                    "architecture", "arm64", null, null, 40),
            rule(ResourceType.RDS, "instance", "rds_instance_hour", "instanceType", null, null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.RDS, "storage", "rds_storage_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.REDIS, "node", "redis_node_hour", "nodeType", "nodes", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.ALB, "fixed", "alb_hour", null, null, null, null, true,
                    null, null, "enabled", "false", 10),
            rule(ResourceType.ALB, "lcu", "alb_lcu_hour", null, "estimatedLcu", null, null, true,
                    null, null, "enabled", "false", 20),
            rule(ResourceType.S3, "storage", "s3_standard_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.NAT_GATEWAY, "fixed", "nat_gateway_hour", null, "gatewayCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.NAT_GATEWAY, "processed", "nat_gateway_gb_processed", null, "processedGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.CLOUDFRONT, "transfer", "cloudfront_gb_transfer", null, "dataTransferGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.LAMBDA, "request", "lambda_per_request", null, "requestsPerMonth", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.LAMBDA, "compute", "lambda_gb_second", null, "requestsPerMonth", "avgDurationMs", "memoryMb", false,
                    null, null, null, null, 20, new BigDecimal("0.0000009765625")),
            rule(ResourceType.DYNAMODB, "read", "dynamodb_per_read_unit", null, "monthlyReadRequests", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.DYNAMODB, "write", "dynamodb_per_write_unit", null, "monthlyWriteRequests", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.DYNAMODB, "storage", "dynamodb_storage_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 30),
            rule(ResourceType.EC2, "instance", "ec2_instance_hour", "instanceType", "count", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.EBS, "storage", "ebs_gp3_gb_month", null, "volumeGb", "volumeCount", null, false,
                    null, null, null, null, 10),
            rule(ResourceType.DATA_TRANSFER, "outbound", "data_transfer_out_gb", null, "outboundGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.VPC_ENDPOINT, "hour", "vpc_endpoint_hour", null, "count", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.VPC_ENDPOINT, "processed", "vpc_endpoint_gb_processed", null, "processedGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.TRANSIT_GATEWAY, "hour", "transit_gateway_hour", null, "attachmentCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.TRANSIT_GATEWAY, "processed", "transit_gateway_gb_processed", null, "processedGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.VPC_PEERING, "processed", "vpc_peering_gb_processed", null, "processedGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.API_GATEWAY, "request", "api_gateway_http_per_request", null, "requestsPerMonth", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.SQS, "request", "sqs_per_request", null, "requestsPerMonth", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.SNS, "request", "sns_per_request", null, "requestsPerMonth", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.EFS, "storage", "efs_standard_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.AURORA, "acu", "aurora_serverless_acu_hour", null, "acu", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.AURORA, "storage", "aurora_storage_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.OPENSEARCH, "instance", "opensearch_instance_hour", "instanceType", "nodeCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.OPENSEARCH, "storage", "opensearch_gp3_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.SECRETS_MANAGER, "secret", "secrets_manager_per_secret_month", null, "secretCount", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.SECRETS_MANAGER, "api-request", "secrets_manager_per_api_request", null, "apiRequestsPerMonth", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.ROUTE53, "hosted-zone", "route53_hosted_zone_month", null, "hostedZoneCount", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.ROUTE53, "query", "route53_per_query", null, "monthlyQueries", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.EVENTBRIDGE, "event", "eventbridge_per_event", null, "monthlyEvents", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.STEP_FUNCTIONS, "standard-transition", "step_functions_per_state_transition", null,
                    "monthlyExecutions", "transitionsPerExecution", null, false,
                    "workflowType", "standard", null, null, 10),
            rule(ResourceType.CLOUDWATCH, "logs-ingest", "cloudwatch_logs_ingest_gb", null, "monthlyIngestGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.CLOUDWATCH, "logs-storage", "cloudwatch_logs_storage_gb_month", null, "storedGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.CLOUDWATCH, "alarm", "cloudwatch_alarm_month", null, "alarmCount", null, null, false,
                    null, null, null, null, 30),
            rule(ResourceType.KINESIS, "shard", "kinesis_shard_hour", null, "shardCount", null, null, true,
                    "streamMode", "provisioned", null, null, 10),
            rule(ResourceType.KINESIS, "put-payload", "kinesis_put_payload_unit", null, "monthlyPutPayloadUnits", null, null, false,
                    "streamMode", "provisioned", null, null, 20),
            rule(ResourceType.WAF, "web-acl", "waf_web_acl_month", null, "webAclCount", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.WAF, "rule", "waf_rule_month", null, "ruleCount", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.WAF, "request", "waf_per_request", null, "monthlyRequests", null, null, false,
                    null, null, null, null, 30),
            rule(ResourceType.SES, "recipient", "ses_per_recipient", null, "recipientsPerMonth", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.SES, "attachment", "ses_attachment_gb", null, "attachmentGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.EKS, "cluster", "eks_cluster_hour", "controlPlaneTier", "clusterCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.ECR, "storage", "ecr_storage_gb_month", "storageClass", "storageGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.CLOUDTRAIL, "management-event", "cloudtrail_paid_event", null, "managementEvents", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.CLOUDTRAIL, "data-event", "cloudtrail_data_event", null, "dataEvents", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.CLOUDTRAIL, "query", "cloudtrail_query_gb", null, "queryGb", null, null, false,
                    null, null, null, null, 30),
            rule(ResourceType.GLUE, "etl", "glue_dpu_hour", "jobType", "etlDpuHours", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.GLUE, "crawler", "glue_crawler_dpu_hour", null, "crawlerDpuHours", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.ATHENA, "query", "athena_scanned_tb", null, "scannedTb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.REDSHIFT, "node", "redshift_ra3_large_hour", "nodeType", "nodeCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.REDSHIFT, "storage", "redshift_storage_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.MSK, "broker", "msk_broker_hour", "brokerType", "brokerCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.MSK, "storage", "msk_storage_gb_month", null, "storageGb", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.APPSYNC, "graphql-request", "appsync_graphql_request", null, "graphqlRequests", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.APPSYNC, "realtime-minute", "appsync_realtime_minute", null, "realtimeMinutes", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.COGNITO, "mau", "cognito_mau", "tier", "monthlyActiveUsers", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.BEDROCK, "input", "bedrock_nova_lite_input_1k_tokens", "model", "input1kTokens", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.BEDROCK, "output", "bedrock_nova_lite_output_1k_tokens", "model", "output1kTokens", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.SAGEMAKER, "hosting", "sagemaker_ml_m5_large_hour", "instanceType", "instanceCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.SSM, "advanced-parameter", "ssm_advanced_parameter_month", "parameterTier", "advancedParameters", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.SSM, "parameter-api", "ssm_parameter_api_request", null, "apiRequests", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.KMS, "key", "kms_key_month", null, "keyCount", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.KMS, "request", "kms_request", "requestType", "requests", null, null, false,
                    null, null, null, null, 20),
            rule(ResourceType.CLOUDHSM, "hsm", "cloudhsm_hour", "hsmType", "hsmCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.BACKUP, "warm-storage", "backup_warm_storage_gb_month", "backupResource", "warmStorageGb", null, null, false,
                    null, null, null, null, 10),
            rule(ResourceType.NLB, "hour", "nlb_hour", null, "balancerCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.NLB, "lcu", "nlb_lcu_hour", null, "lcu", null, null, true,
                    null, null, null, null, 20),
            rule(ResourceType.GWLB, "hour", "gwlb_hour", null, "balancerCount", null, null, true,
                    null, null, null, null, 10),
            rule(ResourceType.GWLB, "lcu", "gwlb_lcu_hour", null, "lcu", null, null, true,
                    null, null, null, null, 30)
    );

    private static ResourcePricingRule rule(
            ResourceType resourceType,
            String componentName,
            String priceKey,
            String optionField,
            String quantityField,
            String quantityField2,
            String quantityField3,
            boolean multiplyHours,
            String conditionField,
            String conditionValue,
            String disabledWhenField,
            String disabledWhenValue,
            int ruleOrder
    ) {
        return rule(resourceType, componentName, priceKey, optionField, quantityField, quantityField2, quantityField3,
                multiplyHours, conditionField, conditionValue, disabledWhenField, disabledWhenValue,
                ruleOrder, BigDecimal.ONE);
    }

    private static ResourcePricingRule rule(
            ResourceType resourceType,
            String componentName,
            String priceKey,
            String optionField,
            String quantityField,
            String quantityField2,
            String quantityField3,
            boolean multiplyHours,
            String conditionField,
            String conditionValue,
            String disabledWhenField,
            String disabledWhenValue,
            int ruleOrder,
            BigDecimal multiplier
    ) {
        return new ResourcePricingRule(
                resourceType,
                componentName,
                ResourcePricingFormulaType.PRICE_TIMES_FACTORS,
                priceKey,
                optionField,
                quantityField,
                quantityField2,
                quantityField3,
                multiplier,
                multiplyHours,
                conditionField,
                conditionValue,
                disabledWhenField,
                disabledWhenValue,
                ruleOrder
        );
    }
}
