package com.awscalculator.backend.pricing;

import java.math.BigDecimal;
import java.util.Map;

/** Mirrors src/main/resources/pricing/&lt;region&gt;-pricing.json, produced by scripts/fetch_pricing.sh. */
public record PricingSnapshot(
        Meta meta,
        BigDecimal hoursPerMonth,
        BigDecimal usdToKrw,
        Map<String, BigDecimal> ec2InstanceHour,
        BigDecimal ebsGp3GbMonth,
        BigDecimal natGatewayHour,
        BigDecimal natGatewayGbProcessed,
        Map<String, BigDecimal> rdsInstanceHour,
        BigDecimal rdsStorageGbMonth,
        Map<String, BigDecimal> redisNodeHour,
        BigDecimal fargateVcpuHourX86,
        BigDecimal fargateGbHourX86,
        BigDecimal fargateVcpuHourArm,
        BigDecimal fargateGbHourArm,
        BigDecimal albHour,
        BigDecimal albLcuHour,
        BigDecimal s3StandardGbMonth,
        BigDecimal cloudFrontGbTransfer,
        BigDecimal lambdaPerRequest,
        BigDecimal lambdaGbSecond,
        BigDecimal dynamoDbPerReadUnit,
        BigDecimal dynamoDbPerWriteUnit,
        BigDecimal dynamoDbStorageGbMonth,
        BigDecimal dataTransferOutGb,
        BigDecimal vpcEndpointHour,
        BigDecimal vpcEndpointGbProcessed,
        BigDecimal transitGatewayHour,
        BigDecimal transitGatewayGbProcessed,
        BigDecimal vpcPeeringGbProcessed,
        BigDecimal apiGatewayHttpPerRequest,
        BigDecimal sqsPerRequest,
        BigDecimal snsPerRequest,
        BigDecimal efsStandardGbMonth,
        BigDecimal s3StandardIaGbMonth,
        BigDecimal ebsGp2GbMonth,
        BigDecimal ebsIo2GbMonth,
        Map<String, BigDecimal> rdsInstanceHourMultiAz,
        BigDecimal lambdaPerRequestArm,
        BigDecimal lambdaGbSecondArm,
        BigDecimal dynamoDbProvisionedReadUnitHour,
        BigDecimal dynamoDbProvisionedWriteUnitHour,
        BigDecimal auroraServerlessAcuHour,
        BigDecimal auroraStorageGbMonth,
        Map<String, BigDecimal> openSearchInstanceHour,
        BigDecimal openSearchGp3GbMonth,
        BigDecimal secretsManagerPerSecretMonth,
        BigDecimal secretsManagerPerApiRequest,
        BigDecimal route53HostedZoneMonth,
        BigDecimal route53PerQuery,
        BigDecimal eventBridgePerEvent,
        BigDecimal stepFunctionsPerStateTransition,
        BigDecimal cloudWatchLogsIngestGb,
        BigDecimal cloudWatchLogsStorageGbMonth,
        BigDecimal cloudWatchAlarmMonth,
        BigDecimal kinesisShardHour,
        BigDecimal kinesisPutPayloadUnit,
        BigDecimal wafWebAclMonth,
        BigDecimal wafRuleMonth,
        BigDecimal wafPerRequest,
        BigDecimal sesPerRecipient,
        BigDecimal sesAttachmentGb,
        Map<String, BigDecimal> eksClusterHour,
        Map<String, BigDecimal> ecrStorageGbMonth,
        BigDecimal cloudTrailPaidEvent,
        BigDecimal cloudTrailDataEvent,
        BigDecimal cloudTrailQueryGb,
        Map<String, BigDecimal> glueDpuHour,
        BigDecimal glueCrawlerDpuHour,
        BigDecimal athenaScannedTb,
        Map<String, BigDecimal> redshiftRa3LargeHour,
        BigDecimal redshiftStorageGbMonth,
        Map<String, BigDecimal> mskBrokerHour,
        BigDecimal mskStorageGbMonth,
        BigDecimal appSyncGraphqlRequest,
        BigDecimal appSyncRealtimeMinute,
        Map<String, BigDecimal> cognitoMau,
        Map<String, BigDecimal> bedrockNovaLiteInput1kTokens,
        Map<String, BigDecimal> bedrockNovaLiteOutput1kTokens,
        Map<String, BigDecimal> sageMakerMlM5LargeHour,
        Map<String, BigDecimal> ssmAdvancedParameterMonth,
        BigDecimal ssmParameterApiRequest,
        BigDecimal kmsKeyMonth,
        Map<String, BigDecimal> kmsRequest,
        Map<String, BigDecimal> cloudHsmHour,
        Map<String, BigDecimal> backupWarmStorageGbMonth,
        BigDecimal nlbHour,
        BigDecimal nlbLcuHour,
        BigDecimal gwlbHour,
        BigDecimal gwlbLcuHour
) {
    public record Meta(String region, String source, String fetchedAt) {
    }
}
